ntp_timezone: '{{ timezone }}'

locale: en_US.UTF-8

dns_nameservers: ['1.1.1.1', '1.0.0.1']

fish_prompt_color: orange

keyboard_layout: us

default_username: rocky

default_guid: '1000'

default_shell: /usr/bin/fish

media_username: jellyfin

media_guid: '1003'

media_shell: /usr/bin/bash



docker_dir: /opt/docker/data

dotfiles_repo: https://github.com/notthebee/dotfiles

boot_drive_serial: ''


extra_packages:
    - fish
    - iperf3
    - btop
    - stow
    - git
    - screen
    - rsync


security_ssh_port: 69

security_sudoers_passwordless: ['{{ username }}']

security_autoupdate_reboot: true

security_autoupdate_mail_to: '{{ email }}'

security_autoupdate_reboot_time: '23:00'

security_autoupdate_mail_on_error: false




samba_shares:
    - name: Trash
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      owner: '{{ username }}'
      browseable: yes
      path: '{{ mergerfs_root }}'
      valid_users: '{{ username }}, {{ additional_users[0].name }}'
      write_list: '{{ username }}, {{ additional_users[0].name }}'

    - name: Downloads
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      browseable: yes
      owner: '{{ username }}'
      path: '{{ mergerfs_root }}/Downloads'
      valid_users: '{{ username }}, {{ additional_users[0].name }}'
      write_list: '{{ username }}, {{ additional_users[0].name }}'

    - name: Media
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      browseable: yes
      owner: '{{ media_username }}'
      path: '{{ mergerfs_root }}/Media'
      valid_users: '{{ username }}, {{ additional_users[0].name }}'
      write_list: '{{ username }}, {{ additional_users[0].name }}'
